/** Demo props (Remotion Studio preview and a smoke render). Real renders always pass --props. */
import type {CaptionStyle, OverlayProps, TextStyle} from './schema';

const captionStyle: CaptionStyle = {
  font: 'Montserrat',
  weight: 800,
  sizePx: 76,
  strokePx: 7,
  strokeColor: '#000000',
  color: '#FFFFFF',
  highlightColor: '#FFD400',
  background: null,
  animation: 'pop',
  shadow: true,
  highlightLeadFrames: 2,
  maxLines: 1,
  letterSpacingEm: 0,
  lineHeight: 1.12,
};

const titleStyle: TextStyle = {
  font: 'Montserrat',
  weight: 900,
  sizePx: 84,
  color: '#FFFFFF',
  background: null,
  strokePx: 8,
  strokeColor: '#000000',
  align: 'center',
};

export const defaultOverlayProps: OverlayProps = {
  version: 1,
  width: 1080,
  height: 1920,
  fps: 30,
  durationInFrames: 180,
  safe: {top: 288, bottom: 672, left: 65, right: 192},
  captionLayout: {xCenterPx: 540, maxWidthPx: 690, leftPx: 65, rightPx: 888, minScale: 0.72},
  theme: {
    accent: '#FFD400',
    font: 'Montserrat',
    displayFont: 'Anton',
    cardBackground: 'radial-gradient(120% 80% at 50% 28%, #22222a 0%, #0c0c0f 72%)',
    textColor: '#FFFFFF',
  },
  captions: [
    {
      id: 'p001',
      start: 0,
      end: 28,
      yNorm: 0.6,
      style: captionStyle,
      words: [
        {text: 'Most', start: 0, end: 8, emphasis: false},
        {text: 'people', start: 8, end: 17, emphasis: false},
        {text: 'cut', start: 17, end: 27, emphasis: false},
      ],
    },
    {
      id: 'p002',
      start: 30,
      end: 62,
      yNorm: 0.6,
      style: captionStyle,
      words: [
        {text: 'way', start: 32, end: 40, emphasis: false},
        {text: 'too', start: 40, end: 48, emphasis: false},
        {text: 'much.', start: 48, end: 60, emphasis: true},
      ],
    },
  ],
  texts: [
    {
      id: 't001',
      kind: 'hook_title',
      text: 'Stop over-editing',
      items: [],
      itemStarts: [],
      start: 0,
      end: 70,
      xNorm: 0.5,
      yNorm: 0.2,
      style: titleStyle,
      accent: '#FFD400',
      animation: 'pop',
      maxWidthPx: 800,
    },
  ],
  cards: [
    {
      id: 'i001',
      template: 'stat',
      title: 'of viewers watch muted',
      subtitle: 'Verizon / Publicis survey, 2019',
      body: '',
      items: [],
      number: '69%',
      unit: null,
      accent: '#FFD400',
      background: 'radial-gradient(120% 80% at 50% 28%, #22222a 0%, #0c0c0f 72%)',
      start: 100,
      end: 170,
      rect: null,
      transitionIn: {kind: 'zoom', frames: 7},
      transitionOut: {kind: 'fade', frames: 5},
      font: 'Montserrat',
      displayFont: 'Anton',
      reserveBottomPx: 230,
    },
  ],
  graphics: [
    {
      id: 'g001',
      kind: 'circle',
      start: 70,
      end: 100,
      x: 0.35,
      y: 0.3,
      w: 0.3,
      h: 0.12,
      from: null,
      to: null,
      color: '#FFD400',
      strokePx: 10,
      curvature: 0.2,
      drawFrames: 9,
    },
  ],
  debug: false,
};
